name: CI
on: { pull_request: { }, push: { branches: [ main ] } }
jobs:
  container:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Build container
        uses: infrabits/ci-pack@main
        with:
          image: ghcr.io/${{ github.repository }}:${{ github.sha }}
          builder: tools-harbor.wmcloud.org/toolforge/heroku-builder:24_0.20.7
